fixed some bugs
Some errors still exist:
TypeError: Cannot read property '0' of undefined Error(Maybe Due to asynchronization)
Functions does not work successively